name: tests
# Note: name shows up in a badge. Be careful about renaming.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Gradle
        run: ./gradlew :model:jvmTest :scripting:jvmTest :model:jsTest :scripting:jsTest
